### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isFile' of undefined

### ISSUE THREAD

**Issue by timwis** [stackcss/sheetify#100]
If you're receiving the error

```
Uncaught TypeError: Cannot read property 'isFile' of undefined
```

You probably forgot to tell browserify/budo to use the `sheetify/transform`.

```bash
browserify index.js -t sheetify/transform -o bundle.js
```

```bash
budo index.js -- -t sheetify/transform
```

I feel like I run into this error every few days and spend 20 minutes debugging before slapping my forehead. Next time, I'll search the issues and find this thread.

**Comment by yoshuawuyts** [comment]
dammit, ran into this too yesterday - feel like `bankai` is messing up somewhere too

cc/ @kriesse think I found our bug >.<
