### ISSUE TITLE
Lower specificity use case

### ISSUE THREAD

**Issue by kristoferjoseph** [stackcss/sheetify#114]
Been using sheetify recently and really liking it!
Was thinking it would be really nice to be able to support a use case that allows for lower specificity selectors.

basically now you need to do:
`Input`
```
:host > .link {
  color: indigo;
}
```
`output`
```
._39jen2 > .link { color: indigo;}
```

What I'd like to do is:
`Input`
```
:host-link {
  color: indigo;
}
```
`output`
```
._39jen2-link { color: indigo; }
```

thoughts?

**Comment by yoshuawuyts** [comment]
Interesting - you could totes create a transform for this. Right now we're
piggy backing on the :host keyword which was introduced for shadow DOM
stuff, think your proposal wouldn't be spec compliant :/

**Comment by kristoferjoseph** [comment]
totally.
Maybe this is incongruous to what sheetify is trying to do.
Not necessarily wanting to use `:host`, just wanting access to the unique id that it generates.

**Comment by yoshuawuyts** [comment]
Hmm, yeah that can only be done through host at the moment. I think a
transform which mashes up host + following class into a new class should do
the trick tho 😁
