### ISSUE TITLE
Optional sheetify.json?

### ISSUE THREAD

**Issue by jamsinclair** [stackcss/sheetify#120]
Slightly related to #119. I find plugins pollute the package.json browserify property and become a bit cumbersome due to heavy nesting. 

What are gut feelings towards an optional `sheetify.json` file?

E.g.

### `sheetify.json` file with plugins and options defined
```
{
  "use": [
    "sheetify-sass",
    [
      "sheetify-postcss",
      {
        "plugins": [
          "autoprefixer"
        ]
      }
    ]
  ],
  "basedir": "."
}

```

### My now cleaner `package.json`
```
.......
  "browserify": {
    "transform": [
      "sheetify/transform",
      "babelify"
    ]
  }
.......
```

I'm happy to contribute a PR to add this functionality, if contributors/owners are okay with this suggestion and direction 😸

**Comment by yoshuawuyts** [comment]
Nah, not I'm not too interested in this; browserify doesn't have a separate
file either and I think we should kinda follow their lead.

**Comment by jamsinclair** [comment]
Good point, totally makes sense 👍 

Closing, because issue question now answered.
