### ISSUE TITLE
Passing variables and v6

### ISSUE THREAD

**Issue by riccardoerra** [stackcss/sheetify#121]
I'm somehow confused if this has been implemented in v6.
Is this not supposed to work?

index.js
```
var css = require('sheetify')

var prefix = css`
  :root {
    --color: yellow;
  }
`
```

another-file.js
```
var css = require('sheetify')

var prefix = css`
  :host {
    background-color: var(--color);
  }
`

```

**Comment by yoshuawuyts** [comment]
It's been working for me so far, not sure what's up. Got a repro?

**Comment by riccardoerra** [comment]
Sorry, was not working on this for few days. Updated a couple of packages and now everything works fine. Can close.
