### ISSUE TITLE
json file with the prefixes

### ISSUE THREAD

**Issue by jenslind** [stackcss/sheetify#124]
Would be nice to have the option to generate a json file with the generated prefixes. So it can be loaded server-side. I guess this would be a nice use case for a plugin, problem is the prefix is not passed to the plugins.

**Comment by yoshuawuyts** [comment]
Heya,

This should probably be a separate transform/plugin that you run after
sheetify. Perhaps a plugin similar to
https://github.com/stackcss/css-extract/ where you detect all `insert-css`
calls and write them to an object or file or something. Hope that's
helpful. Cheers!

**Comment by yoshuawuyts** [comment]
Think this has been answered - closing
