### ISSUE TITLE
idea: template string interpolation

### ISSUE THREAD

**Issue by jongacnik** [stackcss/sheetify#128]
Curious if interpolation for template strings is something of interest? For example:

```js
var red = '#f00'
var cssString = '.upper { text-transform: uppercase }'

var prefix = css`
  :host {
    background: ${red}
  }

  ${cssString}
`
```

In Node, doing the interpolation itself isn't tooo bad if we parse sheetify args and pass into a thing like:

```js
// v simplified for example sake!
function sheetify () {
  var args = Array.prototype.slice.apply(arguments)
  var css = interpolate(args[0], args.slice(1))
  // ...etc
}

function interpolate (strs, vals) {
  return strs.map(function (str, i) {
    return str + (vals[i] || '')
  }).join('')
}
```

But! It seems like the complication is the browserify transform. Ideally the transform would actually execute the js so the `insert-css()` call has no additional overhead. But perhaps a transform like yo-yoify where calls to sheetify w/in the source are converted into plain functions could work too?

I took a look at implementing this today, but I'm quite unfamiliar with writing browserify transforms, and as I was banging head against wall figured I'd stop and check to see if this even falls within the sheetify radar 📡🖖

**Comment by yoshuawuyts** [comment]
Oh man, this is non-trivial to get done haha. You're totally right lmao,
we'd need a partial
JS interpreter to evaluate what the result should be, and interpolate that.
We've def
discussed this in the past, but I believe nobody felt like they had the
bandwidth to take it
on - if you feel like doing it, it'd be cool tho! - People have asked for
this in the past, and
I'd def be open to the addition :D

**Comment by jongacnik** [comment]
Yaaaa lol I think when I have a free weekend I might take another crack, but it's tootally non-trivial ! Not sure if we should leave this open or not.. Gonna take some time either way 🍺😵

**Comment by ahdinosaur** [comment]
hey @jongacnik, i've put some effort into this before: https://github.com/stackcss/sheetify/issues/97#issuecomment-251000982 (and a few unpublished attempts to add support `sheetify` and in relevant dependencies). but yes it's non-trivial, i gave up. :smile_cat:

**Comment by jongacnik** [comment]
Hey all @ahdinosaur @yoshuawuyts ! Jumping back in here since #134 pretty much solves this for us! This added support to require node modules via the transform, something like:

**style.js**

```js
var red = '#f00'

module.exports = `
 :host {
    color: ${red}
  }
`
```

**app.js**

```js
var css = require('sheetify')
var html = require('bel')

var prefix = css('./style.js')

document.body.appendChild(html`
  <div class="${prefix}">bam!</div>
`)
```

wonder if we should call this closed 🤔 ?

**Comment by yoshuawuyts** [comment]
Woot! Yeah, think this good to close (:
