### ISSUE TITLE
6.1.1 was a breaking change

### ISSUE THREAD

**Issue by ralphtheninja** [stackcss/sheetify#131]
See https://github.com/datproject/dat-desktop/issues/436

**Comment by yoshuawuyts** [comment]
All we did was upgrade falafel https://github.com/stackcss/sheetify/commit/3f8adb448370d69e7c97c15753d370912158e3f4, ghmmmm

**Comment by ralphtheninja** [comment]
@yoshuawuyts Aye, I don't have more information than this sorry :/

**Comment by ralphtheninja** [comment]
@yoshuawuyts I've been reducing down `elements/modal.js` in the `dat-desktop` project to reach a simpler test case and in the process of doing that I noticed something interesting which I can't wrap my head around, but maybe you can help me out understanding what's going on here.

This works (don't mind `FOO`, `BAR` etc):

```
$ browserify -t sheetify/transform yep.js
```

`yep.js`

```js
function FOO () {                                     
  return `<p>${BAR('foo', { class: 'whatevah' })}</p>`
}                                                     
```

This does _not_ work:

```
$ browserify -t sheetify/transform nope.js
```

`nope.js` (note that I've only added a commented require of sheetify)

```js
// require('sheetify')                                
                                                      
function FOO () {                                     
  return `<p>${BAR('foo', { class: 'whatevah' })}</p>`
}                                                     
```

**Comment by yoshuawuyts** [comment]
Yeah, it looks like Acorn isn't digging it; not really something inside
Sheetify itself. Wonder if it's the `class` keyword inside it that's
messing it up, ghmmm.
