### ISSUE TITLE
[Question]Omitting `:host`

### ISSUE THREAD

**Issue by verpixelt** [stackcss/sheetify#138]
I'm a bloody beginner when it comes to sheetify. Running a default `create-choo-app` and skimmed the README. As far as I understand, I have to use `:host { ... }` every time I want to create a name-spaced class. Now this makes sense to me if one uses chaining, e.g.: `:host > h1`.

I cannot bring myself to style by targeting elements directly. Meaning I'd rather create classes for every element I want to adjust. In that case writing `:host {}` over and over again becomes redundant.

So I started wondering if it came up already and if you've maybe even considered making it possible to omit `:host` if there is only one target element:

```
const body = css`
  color: palevioletred;
  font-family: sans-serif;
  font-size: 1.2em;
`
```

Edit: I now have a better grasp about the technical necessity of `:host`. I guess what I'm asking for is a less redundant syntax.

**Comment by yoshuawuyts** [comment]
A way to perhaps write this would be to do:
```js
const body = css`:host{
  color: palevioletred;
  font-family: sans-serif;
  font-size: 1.2em;
}`
```
Our philosophy is sorta to only allow valid CSS to be written; something that other solutions don't necessarily offer. In the case of Sheetify this means that extending the above base class to include pseudo-selectors becomes trivial:

```js
const body = css`:host{
  color: palevioletred;
  font-family: sans-serif;
  font-size: 1.2em;
}

:host:hover {
  font-size: 1.6em;
}`
```

Would this work for you?

**Comment by toddself** [comment]
@verpixelt you are targeting elements directly when you use that style.  Sheetify is creating a unique class name each time you invoke it and you're just assigning that class name to your element directly.  This is the same thing as doing a single stylesheet and defining your own class names and just manually assigning them.

The end result with what you're doing is ending up with a single stylesheet with randomly generated class names are that are then being added to the classList for each element.

What it sounds like you want is inline styles perhaps?

**Comment by verpixelt** [comment]
I had some time to think about my issue. Both of your answers have helped a bit.
Thanks to having written CSS over years spread across different stylesheets I've learned to avoid having selector chains especially ones which end in element selectors e.g.: `.some-class h1`.
Main reason, if you change the markup e.g.: h1 becomes h2 you not only have to change the markup you have to find the responding selector chain and adjust this as well.

This is where my issue with the sheetify aka. shadow DOM syntax originated from. I looked at it with the eyes of wanting to write classes for everything instead of creating chains e.g.: `:host h1`.

But creating small components which only have a certain amount of elements + having the CSS next to the markup in the same file makes my initial issue somewhat irrelevant. It might even help to keep components smaller.

Thanks for your answers.
(I hope my explanation is somewhat understandable)
