### ISSUE TITLE
Changing CSS when using Bankai does not re-render the document on the dev server

### ISSUE THREAD

**Issue by stephenkistner** [stackcss/sheetify#144]
Apologies if any of this isnt clear — I have only basic working knowledge of what's going on with sheetify.

I'm working with choo/bankai and sheetify-sass to build a modular library of sass files. Whenever I make a change to one of my .scss files, the css isnt updated and re-rendered on the local dev server.

Seems like there's a few issues posted over on choojs/bankai, and it was asked to post it here, and it hasnt been yet.

Let me know if any other info is required from me.

**Comment by yoshuawuyts** [comment]
@stephenkistner Wrote a fix in #145, if you could take it for a spin / review it'd be very helpful. Thanks! :grin:

**Comment by stephenkistner** [comment]
Yes it works!!!!! Thanks for fixing it so quickly. Hopefully it gets committed soon!

**Comment by yoshuawuyts** [comment]
woooot! :tada: - merged in `sheetify@7.1` :sparkles:
