### ISSUE TITLE
Running into issues with CSS changes in nested files not being reflected in dev environment

### ISSUE THREAD

**Issue by stephenkistner** [stackcss/sheetify#146]
Seems like this is connected to the previous issue where sheetify wasn't passing along file changes at all...

Currently experiencing this using two different approaches:

1. Using sheetify-sass, and when I change something in _vars.scss, which is @imported into main.scss, I have to make a change/re-save main.scss for the changes to be picked up by the dev server.

2. Using the CSS approach that choojs/website uses, with modular .js files that contain CSS which is then packaged under one index.js file that calls sheetify. Same issue — when editing code within the modular js files, CSS changes aren't reflected until I manually save/update the top-level index.js file that links them all together.

Let me know if you need me to provide any more details.

**Comment by yoshuawuyts** [comment]
Oh odd, so there's two things we ought to do here:

- allow Sheetify to listen to `'file'` events on its transforms, and whenever an event is emitted, it emits one itself (which in turn is forwarded to Watchify)
- make `sheetify-sass` emit those events whenever a new file is encountered. Not sure how to approach this, but there's not a lot more we could do otherwise. Worst case we could resort to regex parsing to get the filenames out.

**Comment by stephenkistner** [comment]
Hey here's a quick fresh test I did to reproduce the issue. My github is messed up after enabling 2FA so hopefully this includes everything you need. Just a fresh create-choo-app install, then installing sheetify-sass and then checking to confirm that everything is updated.

https://github.com/stephenkistner/sheetify-scss-test

**Comment by goto-bus-stop** [comment]
> make sheetify-sass emit those events whenever a new file is encountered. Not sure how to approach this, but there's not a lot more we could do otherwise. Worst case we could resort to regex parsing to get the filenames out.

node-sass has an `includedFiles` property on its result object containing absolute paths to all the files so that should be useful :)

**Comment by goto-bus-stop** [comment]
How should we go about this? Allow transforms to return a `{ css: string, files: Array<string> }` object instead of just the `css`, so we can emit 'file' events in sheetify?

**Comment by yoshuawuyts** [comment]
@goto-bus-stop oh, I was thinking a better way would be if a transform could emit it themselves. They already return a stream, which is an event emitter, so hooking into the emitter a-la browserify might make a lot of sense. In turn we can then forward the events to `sheetify`'s main stream, which is then picked up by `watchify`.

E.g. something along the lines of:

```js
var through = require('through2')
var sass = require('sass')

module.exports = function myTransform (filename, opts) {
  var str = through(concat, sink)
  function concat () {
    // aggregate all data from the stream into "rawData"
  }

  function sink () {
    var res = sass(rawData)
    res.files.forEach((file) => str.emit('file', file)) // This is the important part; emit a 'file' event on the returned stream.
    this.emit('end', res.css)
  }
}

**Comment by goto-bus-stop** [comment]
that would be ideal but it does not look like they are streams currently:

https://github.com/stackcss/sheetify/blob/master/index.js#L108-L113

**Comment by yoshuawuyts** [comment]
@goto-bus-stop lmao, looks like we messed up in the design haha. Yeah, guess what you're suggesting makes a lot of sense!

**Comment by goto-bus-stop** [comment]
https://github.com/stackcss/sheetify/pull/147

**Comment by goto-bus-stop** [comment]
sheetify@7.2.0 + sheetify-sass@2.1.0 should do it!
