### ISSUE TITLE
Stripping CSS comments

### ISSUE THREAD

**Issue by chinedufn** [stackcss/sheetify#151]
I'd like to have the option to remove all comments so that I can comment liberally and not worry about accidentally leaking more implementation details into production than necessary.

There is [only one way to comment in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/Comments), so this shouldn't be a big code endeavor. 

Seems like just look for a `/*` and then rip out anything up until the first `*/` that we see.

Just comes down to how we would want to do it.

# Potential Solution 1

```sh
browserify -t [sheetify --strip-comments]
```

---

Happy to PR any solution that y'all are cool with it!

**Comment by yoshuawuyts** [comment]
Not opposed to this, but I also think this would make for a great `sheetify` transform:

```sh
$ browserify -t [sheetify -t sheetify-strip-comments ]
```

In a sense this is similar to `minification`, and Browserify doesn't do anything about that either (for better or worse). Sort of +0 on this feature, but happy to accept PRs if you think it's better in core than in a module :sparkles:

**Comment by chinedufn** [comment]
Great idea - done - thanks! https://github.com/chinedufn/sheetify-strip-comments
