### ISSUE TITLE
Nested dependency - how to with browserify?

### ISSUE THREAD

**Issue by rook2pawn** [stackcss/sheetify#161]
I have a module that i use ```browserify -t sheetify app.js -o bundle.js``` .. however within `app.js` requires another module that requires sheetify transform. The nested dependency doesn't transform correctly as it doesn't inline the css.. How do i correctly do this? I'm guessing the dependency has to specify the transform within its package.json, is that correct?

**Comment by goto-bus-stop** [comment]
yea, an npm package that uses sheetify should specify it as a transform in its package.json.

barring that you can try running sheetify globally using `-g sheetify`, or selectively on the dependency using [tfilter](https://github.com/goto-bus-stop/tfilter):

```bash
browserify -g [ tfilter --include 'node_modules/depname/**/*.js' sheetify ]
```

**Comment by rook2pawn** [comment]
That worked, thank you!
