### ISSUE TITLE
Javascript styles

### ISSUE THREAD

**Issue by ajoslin** [stackcss/sheetify#65]
I'd like to be able to do:

```js
var sf = require('sheetify-js')

var className = sf({
  foo: {
    fontSize: 20
  }
})
```

This seems like it really doesn't need to be in Sheetify core, it can just be a wrapper. Similar to sheetify-sass, there can be sheetify-js.

I could implement this, but first I need to find a good library for transforming a json object to css. Does it exist? I've had a hard time finding anything good.

**Comment by yoshuawuyts** [comment]
Hey, that's a pretty cool idea. Hmm, yeah a transform that runs before `sheetify` would probably be the best approach. Perhaps [cssjson](https://github.com/aramk/CSSJSON) could be leveraged?

**Comment by ajoslin** [comment]
cssjson has a weird syntax, unfortunately. You have to explicitly set `children` and `attributes`.

There are [some libraries](https://github.com/MicheleBertoli/css-in-js) that do js -> CSS ... but none of them as a standalone component.

Looks like it's time to make a module.

**Comment by yoshuawuyts** [comment]
Good luck!

**Comment by serapath** [comment]
not sure if it helps, but for now, i'm still on `jss` and I define my styles in an es6 template literal and then I apply https://github.com/jsstyles/cli/blob/master/lib/cssToJss.js

... it's not the most elegant or efficient solution, but until i'm more sure which of the css-in-js modules i like the most, `jss` works

**Comment by ajoslin** [comment]
I just found [to-css](https://github.com/joakimbeng/to-css), which looks like **exactly** what I need here.

I'm not sure of when I'll actually publish sheetify-js -- The project I was going to use it for might be canned.

When I need it I'll make it and link it here though.
