### ISSUE TITLE
Live style update

### ISSUE THREAD

**Issue by dfcreative** [stackcss/sheetify#69]
Hi @yoshuawuyts!

I am giving a try to sheetify in [gl-spectrum](https://github.com/dfcreative/gl-spectrum) and constantly stumbling on the following issue.

I use [budo](https://github.com/mattdesl/budo) for developing, and sheetify is enabled as `"browserify": {"transform": ["sheetify/transform"]}` field in `package.json`. Styles are connected as follows:
```js
var sf = require('sheetify');
var cssClass = sf('./index.css');

function Spectrum () {
...
	this.container.classList.add(cssClass);
...
}
```

The problem is that each time when I have to change anything in the `index.css`, I have to restart budo, which is quite annoying tbh.

Is there any sort of workaround, or it is not the sheetify’s concern at all, but rather budo’s?
I might mistaken, but that is not the same for glslify, it updates consistently without server restart.

Thanks.

**Comment by ahdinosaur** [comment]
hmm, that seems like a bug to me, as someone who also likes to write css in external files i'd expect that to work as you describe. we should probably re-open https://github.com/stackcss/sheetify/issues/55? in the meantime, it should work if you write css via template strings.

**Comment by mikkoh** [comment]
@dfcreative I know quite a bit of time has passed but did an error get thrown before `budo` halted?

**Comment by dfcreative** [comment]
@mikkoh AFAIK no. I don’t see any errors in budo logs, tbh I don’t know how to halt budo, I always do <kbd>ctrl</kbd>+<kbd>c</kbd> to stop it.
Btw `budo -- -t sheetify/transform` neither updates styles. I tried also `budo --watch-glob *.css -- -t sheetify/transform`, that neither works.

**Comment by dfcreative** [comment]
That is really unfortunate there is no progress on that. Considering the #78 I think I am going to switch to pure insert-css for now. Prefixing rules as `.<prefix>-rule` is win in readability, isolation and performance over `.<randomId> .rule`.

**Comment by mikkoh** [comment]
@dfcreative did your issue get fixed after this PR https://github.com/stackcss/sheetify/pull/73 ? I fixed some stuff that stopped the live updates from `budo` from dying

**Comment by dfcreative** [comment]
@mikkoh yeah, it did. Thanks! It can be closed I guess?
