### ISSUE TITLE
global option defaults to true?

### ISSUE THREAD

**Issue by mciparelli** [stackcss/sheetify#88]
Tests should answer this but the build is currently failing. From what I can tell, if I don't pass `{ global: false }` I don't get my styles namespaced.

**Comment by mciparelli** [comment]
This seems to happen only when requiring a css from a node_module

**Comment by yoshuawuyts** [comment]
Oh yeah, I believe that's correct - the reasoning was that if you're importing a package from `npm` you probably don't want to have it namespaces. Whereas if you're inlining styles you do. Does this make sense?

**Comment by mciparelli** [comment]
Well now that you put it that way I think that makes sense. I'd say `{ global: true }` is the better default for node_modules. ~~You might want to add a line in the readme about that though~~ it was already there and I didn't read documentation before opening issue :facepunch:

**Comment by yoshuawuyts** [comment]
yay!
