### ISSUE TITLE
Variables don't work in template strings

### ISSUE THREAD

**Issue by bcomnes** [stackcss/sheetify#97]
When you use a template in your tagged template string css, the browserify transform breaks.  

``` js
var aColor = '#fff'

var css = sf`.some-class {
  background-color: ${aColor};
}`
```

```
CssSyntaxError: /Users/bret/repos/hyperamp/renderer/index.js:3:2: Unknown word while parsing file: /Users/bret/repos/hyperamp/renderer/index.js

  1 | .some-class {
  2 |   background-color: ,;
> 3 | }[object Object]
    |  ^
```

I started down the road of correcting the in-node implementation, but we are going to have to statically analyze the template string during the transform somehow.  I'm not too familiar with this kind of thing.  Any ideas?

https://github.com/bcomnes/sheetify/commit/112d7b77448da8f7d73bdbf9bba52171ecab329b

This is related to https://github.com/stackcss/sheetify/issues/54 but specific to the way template variables are busted right now vs how `:host` gets used.

**Comment by ahdinosaur** [comment]
i wrote my thoughts on sheetify static evaluation in https://github.com/stackcss/sheetify/issues/54#issuecomment-247816150. meanwhile support for template strings has been merged into [`static-eval`](https://github.com/substack/static-eval/pull/13). :pineapple:

**Comment by yoshuawuyts** [comment]
Should be fixed in `6.0.1` which has the latest `static-eval` - holler if something's not working as expected

**Comment by ahdinosaur** [comment]
@yoshuawuyts you sure this works? you'd have to gather up and pass in all currently defined variables to `static-eval`, i thought you said you'd rather avoid the complexity.

**Comment by yoshuawuyts** [comment]
Oh, didn't realize that's how it worked - nah this doesn't work then

**Comment by sepiropht** [comment]
i'm using the last version, and it still not fixed

**Comment by yoshuawuyts** [comment]
This is because dynamic code can't be interpreted during compilation. You
can, however, export dynamic code that we can later import from a `.js`
file. See
https://github.com/stackcss/sheetify/commit/5817cb0971b878541e5e5f8bc443d2e7a5c3aa23

**Comment by sepiropht** [comment]
Thanks for the response ,but i don't sure if this solution work for my use case:
 I want to update position of an element with the last coords of mouse pointer. 
I don't know values of my css property in advance.
