### ISSUE TITLE
Don't differentiate between host and non-host 

### ISSUE THREAD

**Issue by Briix** [stackcss/sheetify#98]
Would be really nice to get rid of the special :host selector, so prefixed styles could be used in host and non-hosts element without having to apply specific styles to :host.

**Comment by yoshuawuyts** [comment]
Yeah I'd be keen for this, as it allows us to define non-prefixed styles inline. Given that I'm using tachyons nowadays I don't really use prefixing anymore anyway, and the humans I've seen write prefixed tachyons tend to use `:host` anyway. :+1: from me!

**Comment by ahdinosaur** [comment]
@Briix i'm not sure i understand, is it possible for you to describe more detail with maybe an example?

**Comment by Briix** [comment]
@ahdinosaur Sorry for the really slow response!
Originally :host seemed like an unnecessary selector to me, but I'm actually not so sure anymore.
It was mainly because I've mostly seen sheetify used in two ways:
- to create inline styles, thus using the :host selector
- to create additional styles with selectors or classes

The :host selector doesn't make a lot of sense to me in both of those scenarios. My main frustration was when I wanted to add some additional atomic classes, like `.padding-5vh` etc and then applying those to divs. If I want to apply this to the top level div I have to "prefix" it with `:host` like so: `:host.padding-5vh`. 

I have played around with it some more however, and the above scenario seems to be easily avoided by just adding an outer div the style is applied to.

So it hasn't been as big of a hassle as I originally thought it would be and I can see arguments for keeping/removing it, so I would definitely love some more input and thoughts on it :-)

**Comment by yoshuawuyts** [comment]
I think this might be a reasonable resolution: https://github.com/stackcss/postcss-prefix/pull/9

**Comment by yoshuawuyts** [comment]
Closed in `v6.0.0` :tada:
